# Generated by Django 2.2.3 on 2019-07-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.URLField(max_length=300)),
                ('article_headline', models.CharField(max_length=200)),
                ('aricle_body', models.TextField()),
            ],
        ),
    ]
