# Generated by Django 2.2.3 on 2019-07-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='aricle_body',
            new_name='article_body',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_headline',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_name',
            field=models.URLField(max_length=1000),
        ),
    ]
