# Generated by Django 2.2.3 on 2019-08-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20190723_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='website_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
